# -*- coding: utf-8 -*-
"""Pyannote_single_file

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o45XXrVoeWNEq4Qnh34Q1WROmUSFNR2b
"""
'''
1)Import  wav file and reference rttm in parent directory
2)In terminal run these two commands

chmod +x dscore-master/scorelib/md-eval-22.pl
pip install -r dscore-master/requirements.txt

'''

from pyannote.audio import Pipeline

import os
from pydub import AudioSegment
from pydub.playback import play
import torch

from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization-3.0",use_auth_token="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")

import torch
pipeline.to(torch.device("cuda"))

#change wav file name
diarization = pipeline("aepyx.wav")

for turn, _, speaker in diarization.itertracks(yield_label=True):
    print(f"start={turn.start:.1f}s stop={turn.end:.1f}s speaker_{speaker}")

# dump the diarization output to disk using RTTM format
with open("output.rttm", "w") as rttm:
    diarization.write_rttm(rttm)



